CREATE DATABASE IF NOT EXISTS tree;

CREATE TABLE IF NOT EXISTS NODE (id SERIAL PRIMARY KEY, name VARCHAR(200), path TEXT);

TRUNCATE NODE;

INSERT INTO NODE (NAME, PATH) VALUES ("AAA", "");

INSERT INTO NODE (NAME, PATH) VALUES ("BBB", "AAA|");
INSERT INTO NODE (NAME, PATH) VALUES ("CCC", "AAA|");
INSERT INTO NODE (NAME, PATH) VALUES ("DDD", "AAA|CCC|");
INSERT INTO NODE (NAME, PATH) VALUES ("EEE", "AAA|CCC|");
INSERT INTO NODE (NAME, PATH) VALUES ("FFF", "AAA|CCC|");